/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

type Commit struct {
	Sha string `json:"sha,omitempty"`
	Author string `json:"author,omitempty"`
	Committer string `json:"committer,omitempty"`
	Message string `json:"message,omitempty"`
	Tree string `json:"tree,omitempty"`
	Parents string `json:"parents,omitempty"`
}
