/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

// 创建仓库标签
type ProjectLabel struct {
	Id    int32  `json:"id,omitempty"`
	Name  string `json:"name,omitempty"`
	Ident string `json:"ident,omitempty"`
}
