/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

// create issue information
type IssueCreateParam struct {
	// 用户授权码
	AccessToken string `json:"access_token,omitempty"`
	// 仓库路径(path)
	Repo string `json:"repo,omitempty"`
	// Issue标题
	Title string `json:"title,omitempty"`
	// 企业自定义任务类型，非企业默认任务类型为“任务”
	IssuType string `json:"issu_type,omitempty"`
	// Issue描述
	Body string `json:"body,omitempty"`
	// Issue负责人的username
	Assignee string `json:"assignee,omitempty"`
	// 里程碑序号
	Milestone int32 `json:"milestone,omitempty"`
	// 用逗号分开的标签，名称要求长度在 2-20 之间且非特殊字符。如: bug,performance
	Labels string `json:"labels,omitempty"`
	// 项目ID
	Program string `json:"program,omitempty"`
	// Issue协助者的个人空间地址, 以 , 分隔
	Collaborators string `json:"collaborators,omitempty"`
}
