/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

type SetRepoReviewer struct {
	// 用户授权码
	AccessToken string `json:"access_token,omitempty"`
	// 审查人员
	Assigneers string `json:"assigneers,omitempty"`
	// 测试人员
	Testers string `json:"testers,omitempty"`
	// 最少审查人数
	AssigneersNumber int32 `json:"assigneers_number,omitempty"`
	// 最少测试人员
	TestersNumber int32 `json:"testers_number,omitempty"`
}
